export { countCharacters } from './countCharacters';
export { countSentences } from './countSentences';
export { countWords } from './countWords';
export { countParagraphs } from './countParagraphs';
export { countSearchFrequency } from './countSearchFrequency';
export { estimateReadingTime } from './estimateReadingTime';
export { calculateWordFrequencies } from './calculateWordFrequencies';
export { calculateCharFrequencies } from './calculateCharFrequencies';
export { findMostAndLeastFrequent } from './findMostAndLeastFrequent';
