#!/bin/sh

yarn run prettier:check ||
(
  echo "❌ Prettier check failed. You can use 'yarn prettier:fix'. ❌"
  false;
)

yarn run lint:check ||
(
  echo "❌ ESLint check failed. You can use 'yarn lint:fix'. ❌";
  false;
)

yarn run test ||
(
  echo '❌ Testing failed. ❌';
  false;
)
